  on:
    push:
      branches:
        - "*"

  jobs:
    ci:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: '3.12'
            run: 'python --version'

        - name: Install dependencies
          run: pip install -r requirements.txt